name: Build and Test

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  setup_and_build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are updated

    - name: clang-format
      continue-on-error: true 
      run: |
        find src/ -type f \( -name '*.cpp' -o -name '*.hpp' \) \
          -exec clang-format --dry-run --Werror {} +

    - name: Set up vcpkg
      run: |
        if [ -f ./contrib/vcpkg/.git/shallow ]; then
            git -C ./contrib/vcpkg/ fetch --unshallow
        fi
        
        ./contrib/vcpkg/bootstrap-vcpkg.sh

    - name: Create build directory
      run: mkdir build_release

    - name: Configure with CMake
      run: |
        cd build_release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../contrib/vcpkg/scripts/buildsystems/vcpkg.cmake  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build with CMake
      run: |
        cd build_release
        cmake --build . --config Release --parallel 4

    - name: clang-tidy
      run: |
        chmod +x ./scripts/unix/clang-tidy-check.sh
        ./scripts/unix/clang-tidy-check.sh

    - name: Run tests
      run: |
        ./build_release/tests-libcell